tab_view/devices/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, EmailField, BooleanField, SelectField
from wtforms.validators import DataRequired, Length, Email, EqualTo, Regexp, ValidationError
from tab_view.models import Device


class NewDevice(FlaskForm):
    name = StringField('Device Name', validators=[DataRequired(), Length(max=50)])
    device_url = StringField('Adres URL', validators=[DataRequired(), Regexp(
            r'^[a-zA-Z0-9_-]+$',
            message='The URL can only contain letters, numbers, hyphens, and underscores.'
        )])
    media_id = SelectField('Select media for this device:', coerce=int, validators=[DataRequired()])
    submit = SubmitField('Add')

    def validate_device_url(self, field):
        if Device.query.filter_by(device_url=field.data).first():
            raise ValidationError('This URL is already in use by another device.')


class UpdateDevice(FlaskForm):
    device_id = None
    name = StringField('Device Name', validators=[DataRequired(), Length(max=50)])
    device_url = StringField('Adres URL', validators=[DataRequired(), Regexp(
            r'^[a-zA-Z0-9_-]+$',
            message='The URL can only contain letters, numbers, hyphens, and underscores.'
        )])
    media_id = SelectField('Select media for this device:', coerce=int, validators=[DataRequired()])
    submit = SubmitField('Update')


class DeleteDevice(FlaskForm):
    submit = SubmitField('Delete')

tab_view/devices/__init__.py
from flask import Blueprint


devices_bp = Blueprint('devices', __name__)

from . import routes

tab_view/devices/routes.py
from . import devices_bp
from tab_view import db
from tab_view.models import Device, Media
from .forms import NewDevice, UpdateDevice, DeleteDevice
from flask import request, render_template, flash, redirect, url_for
from flask_login import login_required


@devices_bp.route('/', methods=['GET'])
@login_required
def get_all_devices():
    form = DeleteDevice()

    page = request.args.get('page', 1, type=int)
    per_page = 9
    pagination = Device.query \
        .order_by(Device.id) \
        .paginate(page=page, per_page=per_page)
    
    devices = pagination.items
    return render_template('devices/devices.html',
                           devices=devices,
                           pagination=pagination,
                           form=form)


@devices_bp.route('/<device_url>')
def show_device(device_url):
    device = Device.query.filter_by(device_url=device_url).first_or_404()
    media = device.media
    return render_template('devices/display.html', device=device, media=media)


@devices_bp.route('/new', methods=['GET', 'POST'])
@login_required
def create_device():
    media_list = Media.query.all()
    if not media_list:
        flash("No media available. Add a file before creating the device.", "warning")
        return redirect(url_for('media.new_media'))

    form = NewDevice()
    form.media_id.choices = [(media.id, media.filename) for media in media_list]

    if form.validate_on_submit():
        name = form.name.data
        device_url = form.device_url.data
        media_id = form.media_id.data

        new_device = Device(name=name, device_url=device_url, media_id=media_id)
        db.session.add(new_device)
        db.session.commit()
        flash('Device added successfully!', 'success')
        return redirect(url_for('devices.get_all_devices'))
    return render_template('devices/new-device.html', form=form)


@devices_bp.route('/update/<device_id>', methods=['GET', 'POST'])
@login_required
def update_device(device_id):
    device = Device.query.get_or_404(device_id)

    media_list = Media.query.all()
    if not media_list:
        flash("No media available. Add a file before creating the device.", "warning")
        return redirect(url_for('media.new_media'))
    
    form = UpdateDevice(obj=device)
    form.device_id = device.id
    form.media_id.choices = [(media.id, media.filename) for media in media_list]

    if request.method == 'GET':
        form.name.data = device.name
        form.device_url.data = device.device_url
        form.media_id.data = device.media_id


    if form.validate_on_submit():

        existing_name = Device.query.filter_by(name=form.name.data).first()
        if existing_name and existing_name.id != device.id:
            flash('This device name is already in use.', 'danger')
            return redirect(url_for('devices.update_device', device_id=device.id))

        existing_url = Device.query.filter_by(device_url=form.device_url.data).first()
        if existing_url and existing_url.id != device.id:
            flash('This URL is already assigned to another device.', 'danger')
            return redirect(url_for('devices.update_device', device_id=device.id))

        device.name = form.name.data
        device.device_url = form.device_url.data
        device.media_id = form.media_id.data

        db.session.commit()
        flash('Device updated successfully!', 'success')
        return redirect(url_for('devices.get_all_devices'))
    return render_template('devices/update-device.html', form=form, device=device)


@devices_bp.route('/delete/<device_id>', methods=['POST'])
@login_required
def delete_device(device_id):
    device = Device.query.get_or_404(device_id)
    db.session.delete(device)
    db.session.commit()
    flash('Device deleted successfully!', 'success')
    return redirect(url_for('devices.get_all_devices'))

tab_view/templates/devices/devices.html
{% extends 'layout/base.html' %}



{% block title %}Devices{% endblock %}



{% block content %}
    {% for device in devices %}
        <div class="modal fade" id="deleteDeviceModal{{ device.id }}" tabindex="-1" aria-labelledby="modalTitle" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="modalTitle">Delete {{ device.name }}</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <p class="text-center my-3">Are you sure you want to delete device <strong class="text-primary">{{ device.name }}</strong>?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary btn-lg" data-bs-dismiss="modal">Close</button>
                        <form action="{{ url_for('devices.delete_device', device_id=device.id) }}" method="POST">
                            {{ form.hidden_tag() }}
                            {{ form.submit(class="btn btn-danger btn-lg") }}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

    <h1 class="main-heading">Devices</h1>
    <div class="container">
        <div class="row mb-3">
            <div class="col-md-12">
                <a class="btn btn-primary btn-lg float-end mb-5" role="button" href="{{ url_for('devices.create_device') }}">Create New Device</a>
            </div>
        </div>
        <div class="devices-grid">
            {% for device in devices %}
                <div class="device-box">
                    {% if device.media %}
                        <div class="dropdown">
                            <button class="btn dropdown-toggle device-button" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="bi bi-three-dots-vertical"></i>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{{ url_for('devices.update_device', device_id=device.id) }}">Update</a></li>
                                <li><button type="button" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#deleteDeviceModal{{ device.id }}" data-device-name="{{ device.name }}" data-device-id="{{ device.id }}">Delete</button></li>
                            </ul>
                        </div>
                        {% if device.media.media_type == 'image' %}
                            <img src="{{ url_for('static', filename='uploads/' ~ device.media.filename) }}"
                                alt="{{ device.name }}"
                                class="device-box__img device-img img-fluid">
                        {% elif device.media.media_type == 'video' %}
                            <video class="device-box__video device-video" muted autoplay loop>
                                <source src="{{ url_for('static', filename='uploads/' ~ device.media.filename) }}" type="video/mp4">
                                Your browser does not support video playback.
                            </video>
                        {% else %}
                            <img src="{{ url_for('static', filename='img/default.jpg') }}"
                                alt="Default Media"
                                class="device-box__img device-img img-fluid">
                        {% endif %}
                    {% else %}
                        <img src="{{ url_for('static', filename='img/default.jpg') }}"
                            alt="Default Image"
                            class="device-box__img device-img">
                    {% endif %}
                    <h2 class="device-box__heading device-heading display-3 text-center">{{ device.name }}</h2>
                    <p class="text-center"><a href="{{ url_for('devices.show_device', device_url=device.device_url) }}" class="device-link" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="http://example.com/devices/{{ device.device_url }}" data-bs-custom-class="custom-tooltip">/devices/{{ device.device_url }}</a></p>
                </div>
            {% endfor %}
        </div>

        <!-- pagination -->
        <nav class="mt-4 pagination" aria-label="Page navigation">
            <ul class="pagination mx-auto">
                <li class="page-item">
                    <a class="page-link {% if pagination.page == 1 %}disabled{% endif %}"
                        href="{{ url_for('devices.get_all_devices', page=1) }}" {% if pagination.page==1 %}tabindex="-1" {% endif %}
                        aria-label="First">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% if pagination.has_prev %}
                <li class="page-item"><a class="page-link"
                        href="{{ url_for('devices.get_all_devices', page=pagination.prev_num) }}">{{ pagination.prev_num }}</a></li>
                {% endif %}
                <li class="page-item"><span class="page-link active" href="{{ url_for('devices.get_all_devices', page=page) }}"
                        aria-current="page">{{ pagination.page }}</span></li>
                {% if pagination.has_next %}
                <li class="page-item"><a class="page-link"
                        href="{{ url_for('devices.get_all_devices', page=pagination.next_num) }}">{{ pagination.next_num }}</a></li>
                {% endif %}
                <li class="page-item">
                    <a class="page-link {% if not pagination.page < pagination.pages %}disabled{% endif %}"
                        href="{{ url_for('devices.get_all_devices', page=pagination.pages) }}" aria-label="Last">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
{% endblock %}

tab_view/templates/devices/display.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Display {{ device.name }}</title>

    <!-- Google Fonts - Montserrat -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
        rel="stylesheet">

    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">

    <!-- CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <main class="display-menu">
        {% if media.media_type == 'image' %}
            <img src="{{ url_for('static', filename='uploads/' + media.filename) }}" class="display-img">
        {% elif media.media_type == 'video' %}
            <video autoplay loop muted autoplay class="display-video">
                <source src="{{ url_for('static', filename='uploads/' + media.filename) }}" type="video/mp4">
            </video>
        {% endif %}
    </main>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO"
        crossorigin="anonymous"></script>

    <!-- JS -->
    <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
</body>
</html>

tab_view/templates/devices/new-device.html
{% extends 'layout/base.html' %}



{% block title %}Add New Device{% endblock %}



{% block content %}
    <h1 class="main-heading display-5">Add New Device</h1>
    <div class="container">
        <form action="{{ url_for('devices.create_device') }}" class="form" method="POST" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <div class="mb-3">
                {{ form.name.label(class="form-label") }}
                {{ form.name(class="form-control", placeholder="Enter device name") }}
                {% for error in form.name.error %}
                    <div class="text-danger">{{ error }}</div>
                {% endfor %}
            </div>
            <div class="mb-3">
                {{ form.device_url.label(class="form-label") }}
                <div class="input-group">
                    <span class="input-group-text" id="basic-addon3">http://example.com/devices/</span>
                    {{ form.device_url(class="form-control", placeholder="Enter device URL", **{"aria-describedby": "basic-addon3 basic-addon4"}) }}
                </div>
                {% for error in form.device_url.errors %}
                    <div class="text-danger">{{ error }}</div>
                {% endfor %}
            </div>
            <div class="mb-3">
                {{ form.media_id.label(class="form-label") }}
                {{ form.media_id(class="form-control") }}
                {% for error in form.media_id.errors %}
                    <div class="text-danger">{{ error }}</div>
                {% endfor %}
            </div>
            {{ form.submit(class="btn btn-primary btn-lg") }}
        </form>
    </div>
{% endblock %}

tab_view/templates/devices/update-device.html
{% extends 'layout/base.html' %}



{% block title %}Update Device{% endblock %}



{% block content %}
    <h1 class="main-heading display-5">Update Device</h1>
    <div class="container">
        <form action="{{ url_for('devices.update_device', device_id=device.id) }}" class="form" method="POST" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <div class="mb-3">
                {{ form.name.label(class="form-label") }}
                {{ form.name(class="form-control") }}
                {% for error in form.name.errors %}
                    <div class="text-danger">{{ error }}</div>
                {% endfor %}
            </div>
            <div class="mb-3">
                {{ form.device_url.label(class="form-label") }}
                <div class="input-group">
                    <span class="input-group-text" id="basic-addon3">http://example.com/devices/</span>
                    {{ form.device_url(class="form-control", **{"aria-describedby": "basic-addon3 basic-addon4"}) }}
                </div>
                {% for error in form.device_url.errors %}
                    <div class="text-danger">{{ error }}</div>
                {% endfor %}
            </div>
            <div class="mb-3">
                {{ form.media_id.label(class="form-label") }}
                {{ form.media_id(class="form-control", value=device.media_id) }}
                {% for error in form.media_id.errors %}
                    <div class="text-danger">{{ error }}</div>
                {% endfor %}
            </div>
            {{ form.submit(class="btn btn-primary btn-lg") }}
        </form>
    </div>
{% endblock %}