tab_view/media/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField
from wtforms.validators import DataRequired, Length, Email, EqualTo, Regexp, ValidationError
from flask_wtf.file import FileField, FileAllowed, FileRequired


class MediaUploadForm(FlaskForm):
    file = FileField('Upload File', validators=[FileRequired(), FileAllowed(['jpg', 'jpeg', 'png', 'mp4'], 'Images and Videos only!')])
    submit = SubmitField('Add')


class MediaUpdateForm(FlaskForm):
    filename = StringField('Filename', validators=[DataRequired(), FileAllowed(['jpg', 'jpeg', 'png', 'mp4'], 'Images and Videos only!'), Length(max=255)])
    submit = SubmitField('Update')


class MediaDeleteForm(FlaskForm):
    submit = SubmitField('Delete')
    

tab_view/media/__init__.py
from flask import Blueprint


media_bp = Blueprint('media', __name__)

from . import routes

tab_view/media/routes.py
from werkzeug.utils import secure_filename
from flask import redirect, url_for, render_template, current_app, flash, request
from flask_login import login_required
from . import media_bp
from .forms import MediaUploadForm, MediaUpdateForm, MediaDeleteForm
from tab_view import db, csrf
from tab_view.models import Media, Device
from tab_view.utils import detect_type
import os


@media_bp.route('/')
@login_required
def get_all_media():
    form = MediaDeleteForm()

    page = request.args.get('page', 1, type=int)
    per_page = 10
    pagination = Media.query \
        .order_by(Media.id) \
        .paginate(page=page, per_page=per_page)
    
    media = pagination.items
    return render_template('media/media.html',
                           media=media,
                           pagination=pagination,
                           form=form)


@media_bp.route('/new', methods=['GET', 'POST'])
@login_required
def new_media():
    form = MediaUploadForm()

    if form.validate_on_submit():
        file = form.file.data
        filename = secure_filename(file.filename)
        if len(filename) > 255:
            flash('Filename is too long (max 255 characters).', 'danger')
            return render_template('media/new-media.html', form=form)

        existing = Media.query.filter_by(filename=filename).first()
        if not existing:
            file.save(os.path.join(current_app.static_folder, 'uploads', filename))

            media = Media(filename=filename, media_type=detect_type(filename))
            db.session.add(media)
            db.session.commit()
            flash('Media added successfully!', 'success')
            return redirect(url_for('media.get_all_media'))
        else:
            flash('A file with this name already exists in the database.', 'danger')
    return render_template('media/new-media.html', form=form)


@media_bp.route('/update/<int:media_id>', methods=['GET', 'POST'])
@login_required
def update_media(media_id):
    media = Media.query.get_or_404(media_id)
    form = MediaUpdateForm()

    filename_no_ext, file_ext = os.path.splitext(media.filename)
    file_ext = file_ext.lstrip('.')

    if form.validate_on_submit():
        filename_no_ext = secure_filename(form.filename.data)
        full_filename = f"{filename_no_ext}.{file_ext}"

        existing = Media.query.filter_by(filename=full_filename).first()
        if existing and existing.id != media.id:
            flash('A file with this name already exists.', 'danger')
            return redirect(url_for('media.update_media', media_id=media.id))

        old_path = os.path.join(current_app.static_folder, 'uploads', media.filename)
        new_path = os.path.join(current_app.static_folder, 'uploads', full_filename)

        try:
            os.rename(old_path, new_path)
        except FileNotFoundError:
            flash('Nie znaleziono pliku fizycznego do zmiany nazwy.', 'warning')
            return redirect(url_for('media.update_media', media_id=media.id))

        media.filename = full_filename
        db.session.commit()
        flash('Media updated successfully!', 'success')
        return redirect(url_for('media.get_all_media'))
    return render_template('media/update-media.html', form=form, media=media, 
                           file_ext=file_ext, filename_no_ext=filename_no_ext)


@media_bp.route('/delete/<int:media_id>', methods=['POST'])
@login_required
def delete_media(media_id):
    if media_id == 1:
        flash('The default image cannot be deleted.', 'danger')
        return redirect(url_for('media.get_all_media'))
    
    media = Media.query.get_or_404(media_id)
    file_path = os.path.join(current_app.static_folder, 'uploads', media.filename)

    devices_using_media = Device.query.filter_by(media_id=media.id).all()
    if devices_using_media:
        for device in devices_using_media:
            device.media_id = 1

    try:
        if os.path.exists(file_path):
            os.remove(file_path)
        else:
            flash('Plik fizyczny nie istnieje — usunięto tylko z bazy.', 'warning')
            db.session.delete(media)
            db.session.commit()
            return redirect(url_for('media.get_all_media'))
    except Exception as e:
        flash(f'Błąd podczas usuwania pliku: {str(e)}', 'danger')
        return redirect(url_for('media.get_all_media'))

    db.session.delete(media)
    db.session.commit()
    flash('Media deleted successfully!', 'success')
    return redirect(url_for('media.get_all_media'))

tab_view/templates/media/media.html
{% extends 'layout/base.html' %}



{% block title %}Media{% endblock %}



{% block content %}
    {% for m in media %}
        <div class="modal fade" id="deleteMediaModal{{ m.id }}" tabindex="-1" aria-labelledby="modalTitle" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="modalTitle">Delete {{ m.filename }}</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <p class="text-center my-3">Are you sure you want to delete <strong class="text-primary">{{ m.filename }}</strong>?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary btn-lg" data-bs-dismiss="modal">Close</button>
                        <form action="{{ url_for('media.delete_media', media_id=m.id) }}" method="POST">
                            {{ form.hidden_tag() }}
                            {{ form.submit(class="btn btn-danger btn-lg") }}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

    <h1 class="main-heading">Media</h1>
    <div class="container">
        <div class="row mb-3">
            <div class="col-md-12">
                <a class="btn btn-primary btn-lg float-end mb-5" role="button" href="{{ url_for('media.new_media') }}">Add New Media</a>
            </div>
        </div>
        <div class="media-grid">
            {% for m in media %}
                <div class="media-box">
                    <div class="dropdown">
                        <button class="btn dropdown-toggle media-button" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-three-dots-vertical"></i>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{{ url_for('media.update_media', media_id=m.id) }}">Update</a></li>
                            <li><button type="button" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#deleteMediaModal{{ m.id }}" data-device-name="{{ m.filename }}" data-device-id="{{ m.id }}">Delete</button></li>
                        </ul>
                    </div>
                    {% if m.media_type == 'image' %}
                        <img src="{{ url_for('static', filename='uploads/' ~ m.filename) }}"
                            alt="{{ m.filename }}"
                            class="media-box__img media-img">
                    {% elif m.media_type == 'video' %}
                        <video class="media-box__video media-video" muted autoplay loop>
                            <source src="{{ url_for('static', filename='uploads/' ~ m.filename) }}" type="video/mp4">
                            Your browser does not support video playback.
                        </video>
                    {% endif %}
                    <h2 class="media-box__heading media-heading display-3 text-center">{{ m.filename }}</h2>
                    <p class="text-muted text-center">{{ m.media_type }}</p>
                </div>
            {% endfor %}
        </div>

        <!-- pagination -->
        <nav class="mt-4 pagination" aria-label="Page navigation">
            <ul class="pagination mx-auto">
                <li class="page-item">
                    <a class="page-link {% if pagination.page == 1 %}disabled{% endif %}"
                        href="{{ url_for('media.get_all_media', page=1) }}" {% if pagination.page==1 %}tabindex="-1" {% endif %}
                        aria-label="First">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% if pagination.has_prev %}
                <li class="page-item"><a class="page-link"
                        href="{{ url_for('media.get_all_media', page=pagination.prev_num) }}">{{ pagination.prev_num }}</a></li>
                {% endif %}
                <li class="page-item"><span class="page-link active" href="{{ url_for('media.get_all_media', page=page) }}"
                        aria-current="page">{{ pagination.page }}</span></li>
                {% if pagination.has_next %}
                <li class="page-item"><a class="page-link"
                        href="{{ url_for('media.get_all_media', page=pagination.next_num) }}">{{ pagination.next_num }}</a></li>
                {% endif %}
                <li class="page-item">
                    <a class="page-link {% if not pagination.page < pagination.pages %}disabled{% endif %}"
                        href="{{ url_for('media.get_all_media', page=pagination.pages) }}" aria-label="Last">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
{% endblock %}

tab_view/templates/media/new-media.html
{% extends 'layout/base.html' %}



{% block title %}Add New Media{% endblock %}



{% block content %}
    <h1 class="main-heading display-5">Add New Media</h1>
    <div class="container">
        <form action="{{ url_for('media.new_media') }}" class="form" method="POST" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <div class="mb-3">
                {{ form.file.label(class="form-label") }}
                {{ form.file(class="form-control", accept=".jpg,.jpeg,.png,.mp4", placeholder="Upload a new file") }}
                {% for error in form.file.errors %}
                    <div class="text-danger">{{ error }}</div>
                {% endfor %}
            </div>
            {{ form.submit(class="btn btn-primary btn-lg") }}
        </form>
    </div>
{% endblock %}

tab_view/templates/media/update-media.html
{% extends 'layout/base.html' %}



{% block title %}Update Media{% endblock %}



{% block content %}
    <h1 class="main-heading display-5">Update Media</h1>
    <div class="container">
        <form action="{{ url_for('media.update_media', media_id=media.id) }}" class="form" method="POST" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <p class="mb-3">Filename</p>
            <div class="input-group mb-3">
                {{ form.filename(class="form-control", value=file_no_ext, **{"aria-describedby": "basic-addon2"}) }}
                <span class="input-group-text" id="basic-addon2">{{ file_ext }}</span>
                {% for error in form.filename.errors %}
                    <div class="text-danger">{{ error }}</div>
                {% endfor %}
            </div>
            {{ form.submit(class="btn btn-primary btn-lg") }}
        </form>
    </div>
{% endblock %}